# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_cpp <- function(dir_lhs, dir_rhs, bi_lhs, bi_rhs, lab, p_list, q_vec, n, tr, sb, md_s, md_p, rules, draw_derivation, draw_all, derive_all, formula, improve, heuristic, replace, md_sym, verbose) {
    .Call(`_dosearch_initialize_cpp`, dir_lhs, dir_rhs, bi_lhs, bi_rhs, lab, p_list, q_vec, n, tr, sb, md_s, md_p, rules, draw_derivation, draw_all, derive_all, formula, improve, heuristic, replace, md_sym, verbose)
}

